name: Daily News Email

on:
  schedule:
  - cron: '30 3 * * *'  
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  send-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: python news_emailer.py
